src/android/com/ionicframework/cordova/webview/IonicWebView.java

Make path final to avoid cordova 6.4.0 complaint

---

src/ios/CDVWKWebViewEngine.m

In current master, setServerBasePath is broken.
Using it will load the original www folder and create an infinite loop as setServerPath will call initWebServer and initWebServer will call setServerPath once the server is running.

Fix setServerBasePath

---

CHANGELOG.md

remove references to currently unused variable

remove unused allowremoteconnect value

---

src/ios/GCDWebServer/Responses/GCDWebServerFileResponse.m

Related to https://github.com/ionic-team/cordova-plugin-ionic/issues/100

Override lastModifiedDate with current date to avoid not modified response

---

src/android/com/ionicframework/cordova/webview/IonicWebView.java
src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java
src/ios/CDVWKWebViewEngine.m
src/www/util.js

Add persistServerBasePath function and load the persisted path if set instead of bundled www folder.

Add persistServerBasePath function

---

src/android/com/ionicframework/cordova/webview/IonicWebView.java
src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java

`getContext` was added to the `CordovaInterface` in cordova-android 7

support cordova android 6

---

src/ios/CDVWKWebViewEngine.m

Load local assets if the app is a freshly installed binary

---

src/ios/CDVWKWebViewEngine.m

Return 404 response when file doesn't exist

---

.gitignore
README.md
plugin.xml
src/ios/CDVWKWebViewEngine.m
src/ios/IONAssetHandler.h
src/ios/IONAssetHandler.m

Add URLSchemeHandler for iOS 11+, keep web server for iOS 10 and older.

feat (ios): Add URLSchemeHandler for iOS 11+

---

README.md
src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java

BREAKING CHANGE: changes the default from 1 (never) to 0 (always)
Closes #231

feat: Allows configuration of Mixed Content Mode

---

src/www/util.js

Support converting file urls starting by /

---

src/ios/IONAssetHandler.m

fix(ios): Fix video playback of files with uppercase extension

---

README.md
plugin.xml
src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java
src/android/com/ionicframework/cordova/webview/WebViewLocalServer.java

Allows to use a different Scheme instead of http
Fix #269, #255

feat(Android): Make app Scheme configurable with a preference

---

README.md
package.json
plugin.xml

fix: Set engines to require Cordova CLI 7.1.0 or newer

---

src/android/com/ionicframework/cordova/webview/AndroidProtocolHandler.java
src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java
src/android/com/ionicframework/cordova/webview/WebViewLocalServer.java
src/ios/CDVWKWebViewEngine.m
src/ios/IONAssetHandler.m
src/www/util.js

Make 2.x branch also use a single scheme

fix: Use a single scheme for all files

---

README.md
src/ios/CDVWKWebViewEngine.h
src/ios/CDVWKWebViewEngine.m
src/ios/IONAssetHandler.h
src/ios/IONAssetHandler.m

Allows to use a custom scheme instead of the ionic default one
fix #282

feat(ios): Make iOS app Scheme configurable with a preference

---

README.md
src/ios/CDVWKWebViewEngine.m

Instead of removing the doc I've added a note saying it's removed, so it's easier to spot.

Remove WKSuspendInBackground preference

---

src/ios/CDVWKWebViewEngine.m

Fix autofocus on iOS 12.2

---

src/ios/CDVWKWebViewEngine.m

This reverts commit 71855f1295a51c9ae8ceaec681979bfe4f50f735.

Revert "Fix autofocus on iOS 12.2 (#331)"

---

src/ios/CDVWKWebViewEngine.m

fix(ios): Fix autofocus on iOS 12.2

---

src/ios/CDVWKWebViewEngine.m

fix(ios): show error message when app fails to load (#382)

---

README.md

docs(README): Document ScrollEnabled preference

---

src/ios/CDVWKWebViewEngine.m

fix(ios): make programmatically focus work on iOS 13

---

src/ios/CDVWKWebViewEngine.m

fix(ios): make programmatically focus work on iOS 13 (#438)

---

src/www/util.js

Fix Android 5 convertFileSrc not working issue https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/491

replace startsWith with indexOf

---

src/ios/CDVWKWebViewEngine.m

fix(ios): release userAgentLock for IAB compat

---

src/ios/wk-plugin.js

BREAKING CHANGE: wkRewriteURL was deprecated and has been removed, use
window.Ionic.WebView.convertFileSrc instead

feat(ios): remove wkRewriteURL function
