README.md
src/ios/CDVWKWebViewEngine.m

This PR contains the changes made by @ghenry22 to make the local webserver port configurable in https://github.com/ghenry22/cordova-plugin-ionic-webview and submitted as PR #41.
Since there seems to be reluctance to merge #41 due to the background mode changes, this PR isolates and includes only the configurable port changes to resolve issue #40.
All credit for the changes goes to @ghenry22.

Make local webserver port configurable. Resolves #40.

---

src/ios/CDVWKWebViewEngine.m

Creating this updated PR on behalf of @ghenry22, since the original #45 had conflicts. (Literally just a copy and paste job)
Closes #45 
Closes #57 
@genry22 - if this has your blessing please comment here so that @mlynch can merge it.

add _alwaysRunsAtForegroundPriority setting

---

package.json
plugin.xml
src/android/com/ionicframework/cordova/webview/AndroidProtocolHandler.java
src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java
src/android/com/ionicframework/cordova/webview/WebViewLocalServer.java

Add the missing source-files for Android
Remove the handler that return an empty cordova.js as that's only needed for Capacitor, here we want the real cordova.js
Set the webview's webclient to redirect the shouldInterceptRequest to the local server
Set the autority to localhost:8080 as on iOS, but handle it as local requests.
Make the plugin add the allow-navigation for localhost for Android too

Android improvements

---

plugin.xml
src/ios/CDVWKWebViewEngine.h
src/ios/CDVWKWebViewEngine.m
src/ios/wk-plugin.js
src/www/util.js

As we do on Capacitor, just serve the www folder so angular's base url works

Fix to allow angular base url

---

CHANGELOG.md
src/ios/CDVWKWebViewEngine.m
src/ios/GCDWebServer/Core/GCDWebServer.m
src/ios/GCDWebServer/Core/GCDWebServerPrivate.h

This is an updated PR which completes the background mode functionality on iOS.
Changelog has been updated with details of all changes.
config.xml values are listed, with their defaults, in the changelog.
GCDWebserver is now also kept alive when WKWebview is kept alive
GCDWebserver fixes for broken sockets when resuming from background suspension are added
GCDWebserver updated to 3.4.2 (latest at 19Jun18) only one small change in this update but may as well be current
Note you must have appropriate background mode capability set in xcode for your app and actually be doing the background activity that matches your capability to stay alive in the background.
Even with this setting your app will still be suspended by the OS when it is idle and the OS wants to reclaim resources and will …

Background mode for iOS

---

src/ios/CDVWKWebViewEngine.m

The allowRemote variable was included by accident in a previous PR.  This removes the unused entry.

remove unused allowRemote variable

---

src/ios/CDVWKWebViewEngine.m

issue is `self.CDV_LOCAL_SERVER` is set when server is started, not when the `_file_` route is set up.
The change sets up the `CDV_LOCAL_SERVER` path before both so that it's safely accessible in the file handler.

fix #133 - nil reference to CDV_LOCAL_SERVER

---

src/ios/CDVWKWebViewEngine.m

Change to only persist the update id instead of the whole served path as it will change while in development.
On App start, if an update is persisted, recreate the path to the update folder, matching `cordova.dataDirectory`
Closes #157

Make server path relative

---

src/www/ios/ios-wkwebview-exec.js

As on https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/124 the setTimeout was removed, it could cause problems (none reported at the moment, but you never know).
This should protect from those possible problems as it keeps the behaviour the setTimeout used to have (putting the code into a the queue for the next process tick). 
@ghenry22 can you test this and see if keeps working fine in background?
See related [cordova-plugin-wkwebview-engine PR ](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/49)

Wrap callbackFromNative in Promise.resolve

---

src/ios/CDVWKWebViewEngine.m
src/ios/GCDWebServer/Core/GCDWebServer.m

Add  more server ckecks before loading urls or reloading, also check for socket unknown errors

fix: Add more server checks before loading urls or reloading

---

src/ios/CDVWKWebViewEngine.m

Fixes #176 
credit: @KhanhPhamDinh

fix(ios): fix keyboard displacement bug in iOS 12 WKWebView

---

src/android/com/ionicframework/cordova/webview/WebViewLocalServer.java

Currently, the Android version of the plugin always returns http code 200 no matter if the resource
you're trying to get exists or not. The iOS version does return a specific http code for every case. This makes the two implementations inconsistent. This tries to fix that and get the same expected behavior in both of them.
Note that I've used a 500 code in case the call to the `available` method fails. If this is not right let me know and I'll change it. 😉 
BREAKING CHANGE: Until now, the Android part of the plugin was returning a 200 http code even though
the requested file didn't exist. This behavior was inconsistent with the historical behavior of the
iOS webView. This change makes them both work in the same manner but introduces a breaking change
for the current Android users that are …

feat(WebViewLocalServer.java): return 404 error code when a local file is not found

---

plugin.xml
src/android/com/ionicframework/cordova/webview/AndroidProtocolHandler.java
src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java
src/android/com/ionicframework/cordova/webview/WebViewLocalServer.java
src/www/util.js

Implement ionic-file and ionic-content for Android
closes #204, closes #183

feat(Android): Implement ionic-file and ionic-content urls

---

src/android/com/ionicframework/cordova/webview/AndroidProtocolHandler.java
src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java
src/android/com/ionicframework/cordova/webview/WebViewLocalServer.java
src/ios/CDVWKWebViewEngine.h
src/ios/CDVWKWebViewEngine.m
src/ios/IONAssetHandler.m
src/www/util.js

Use ionic:// for app assets and local files instead of having multiple schemes based on the file
type
fix #258

fix: Use a single scheme for all files

---

src/ios/IONAssetHandler.m

fix(ios): Fix video playback of files with uppercase extension (#264)

---

src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java
src/android/com/ionicframework/cordova/webview/WebViewLocalServer.java

Properly handle requests with Range header and return appropriate headers so audio and video tags
work correcly and you can go forward or backward ond them
fix #248, fix #205, fix #141

fix(Android): Handle Range Requests for proper media file handling

---

README.md
src/ios/CDVWKWebViewEngine.m

Remove WKSuspendInBackground preference as it uses a private API
BREAKING CHANGE: Remove the WKSuspendInBackground preference, so apps relying on that preference will not behave as expected
Closes #286

feat(ios): Remove WKSuspendInBackground preference

---

src/android/com/ionicframework/cordova/webview/AndroidProtocolHandler.java

This PR resolves issues with resolving assets. `realPath` string replace fails as the Hostname for example be `localhost:8080`.

fix: resolve content uri when Hostname includes port

---

src/ios/CDVWKWebViewEngine.m

Show it only when running a debug build, not release builds. Let me know if you want it for release too.
Closes #381

fix(ios): show error message when app fails to load

---

src/android/com/ionicframework/cordova/webview/WebViewLocalServer.java

When using WebAssembly browser do not recognize .wasm extension on Android.

fix(Android): return proper mimeType for wasm files

---

src/ios/IONAssetHandler.m

**Problem**
We are using Ionic inside a bigger project, which is developed natively. To integrate our Ionic part inside the bigger project on iOS, we build a .framework file and distribute that to the developers of the bigger native part.
If it is used that way, Ionic is hangig on splash screen and not loading index.html.
**Solution**
We traced the problem back to the IONAssetHandler. In our case self.basePath is null and stringToLoad (or url.path) contains the fully needed path to index.html. But because the first part of the string concatenation is null, the whole startPath gets null. We fixed this by setting startPath first to an empty string instead of null, if self.basePath has no value.

fix(ionassethandler.m): fix startPath is getting null

---

src/ios/CDVWKWebViewEngine.m

`CDVUserAgentUtil` will be removed in cordova-ios 6, so remove the usages of it, and also implement custom handling of the userAgent to not lose that functionality 
closes #527

feat(ios): implement custom userAgent handling

---

src/ios/CDVWKWebViewEngine.m

Despite it's not needed because it doesn't cause the Apple warnings, as users do text searches they wrongly point to this two references as causing their issues.
So removing them to give people some comfort. 
closes #503

chore: remove UIWebView comment and variable

---

src/ios/CDVWKWebViewEngine.m

To remove the deprecated APIs warnings, use the new APIs that replaced them.

fix(ios): Replace deprecated APIs

---

src/ios/CDVWKWebViewEngine.m

Sister PR for 2.x: PR #532
---
The history of the keyboard dismissal problems are kind of messy so here we go:
The main bug that started this all is reported here:
* [cordova-plugin-ionic-webview #176](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/176)
* [cordova-plugin-wkwebview-engine #71](https://github.com/apache/cordova-plugin-wkwebview-engine/issues/71)
* [cordova-ios #417](https://github.com/apache/cordova-ios/issues/417) Which best identifies the problem.
To summarize: Apple did something and broke a part of WKWebView for iOS 12 and 13.  The problem occurs when the keyboard is dismissed.  **After dismissal the bottom part of the page has a white unused portion / the content behind the keyboard becomes unusable.**
The issue is truly an apple problem.  So this …

fix(ios): avoid app scrolling to top on keyboard hide

---

README.md
src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java

Currently Service Workers are not able to retrieve files served by the local file server. This
change fixes this, allowing to use PWA-like offline caching utils.
This fixes #410

feat(android): proxy service worker requests through local server

---

plugin.xml
src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java

This PR drops support for API 19 and adds support for API 29 and can be merged after cordova-android 9 is released.

BREAKING: remove RequiresApi and drop support for API 19

---

src/ios/wk-plugin.js

BREAKING CHANGE: normalizeURL was deprecated and has been removed, use
window.Ionic.WebView.convertFileSrc instead

feat(ios): remove normalizeURL function
